SELECT 
    h.HISTORY_ID,
    TRUNCATE(
        c.DAILY_FEE * (DATEDIFF(h.END_DATE, h.START_DATE) + 1) * 
        IFNULL((100 - d.DISCOUNT_RATE) / 100.0, 1), 
        0
    ) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
JOIN CAR_RENTAL_COMPANY_CAR c ON h.CAR_ID = c.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d ON c.CAR_TYPE = d.CAR_TYPE
    AND (
        (DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 90 AND d.DURATION_TYPE = '90일 이상') OR
        (DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 30 AND DATEDIFF(h.END_DATE, h.START_DATE) + 1 < 90 AND d.DURATION_TYPE = '30일 이상') OR
        (DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 7 AND DATEDIFF(h.END_DATE, h.START_DATE) + 1 < 30 AND d.DURATION_TYPE = '7일 이상')
    )
WHERE c.CAR_TYPE = '트럭'
ORDER BY FEE DESC, h.HISTORY_ID DESC;